### PR TITLE
Ability to insert media into the front-end post box

### PR DESCRIPTION
**Pull request by scottbasgaard**

### CODE REVIEW

**Comment by willmot** [comment]
@richardswain fancy having a look into this?

**Comment by richardswain** [comment]
screen shot 2015-01-08 at 15 21 38

Tried to enqueue some styles, but it broke more than it fixed, 

`wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' )`
`wp_enqueue_style( 'media-styles', ABSPATH . "wp-includes/css/media-views.css", array(), $version )`

So just fixed up the margin etc

**Comment by richardswain** [comment]
@willmot R/M please, mobile bit dodge tho,

**Comment by willmot** [comment]
@richardswain can you pr the update to apollo into the Human Made Website

**Pull request merged**
