### PR TITLE
First sidebar shouldn't be at the top in single column flow

### PR DESCRIPTION
**Pull request by richardswain**
It's annoying to have to scroll past the sidebar.

screen shot 2014-10-05 at 22 22 51

### CODE REVIEW

**Comment by willmot** [comment]
This deff has the added effect, but agree the implementation isn't ideal. Be good to find a way to achieve this without duplicating in the DOM.

My suggestion is that we move the sidebar below the `#main` content div and then move the new post box out of the sidebar and into the main content div just about the Recent Posts H2.

**Comment by richardswain** [comment]
Duplicate removed, and new post / Recent Updates at top. Search and sidebar at the side

screen shot 2015-01-27 at 20 43 47

In single column, new post & Recent Updates at top

screen shot 2015-01-27 at 20 44 13


and Search and sidebar at the  bottom, 


screen shot 2015-01-27 at 20 44 50

**Comment by willmot** [comment]
🌴👍⛵️

Deploying

**Comment by richardswain** [comment]
@willmot - you may have been too quick off the mark

**Comment by willmot** [comment]
@richardswain forgot the updated submodule needs PR'ing back into the main site :-)

**Comment by richardswain** [comment]
@willmot I have 4 commits in my local branch that were not pushed before you deleted this branch - what do i do now?

**Comment by willmot** [comment]
Doh, sorry! My fault for not waiting for you to label as review/merge.

Here's your other commits: https://github.com/humanmade/apollo/pull/22

**Pull request merged**
